### ISSUE TITLE
選舉看板全記錄中缺少某些選區

### ISSUE THREAD

**Issue by GHolk** [readr-media/news-projects#334]
新竹市議員選區有東南西北香山五個區，
但行政上只分東北香山三個區。
我上傳了南區許修睿的看板照，
但找不到他的名字，發現這個 bug 。

bug 是在 [選舉看板全記錄](https://www.readr.tw/project/election-board) 。

另外這個計劃你們都沒有宣傳嗎？怎麼資料那麼少。
在 g0v 翻到覺得蠻有趣的，有點想拿來當期末報告的題材。

**Comment by tempo0829** [comment]
感謝您提供資訊，很抱歉現在才注意到問題。
若有進一步資料需求，歡迎來信到 readr@readr.tw 詢問
